### ISSUE TITLE
RequireAll::LoadError: Could not require

### ISSUE THREAD

**Issue by dcalixto** [jarmo/require_all#30] opened 2019-08-14 00:30 UTC
First, thank you @jarmo  
but after place some nested controllers the log start to show this:
![reee3](https://user-images.githubusercontent.com/1009077/62986769-764e2680-be13-11e9-870c-4115f3e0a1a6.png)

I've tried to require the file by Dir or

 require folder or file before require_all 

![2019-08-13_21-40](https://user-images.githubusercontent.com/1009077/62986690-20797e80-be13-11e9-868f-e3cf56f90b6f.png)

**Comment by jarmo** [comment] 2019-08-15 06:40
First version is caused by require_all version **2.x** changes introduced by PR #24 (discussion in PR #21). You can either try to downgrade your require_all to version **1.x** and take all the risks discussed in these PR-s or your can try to require all dependencies before require_all statement.

Your second error is not caused anymore by require_all, but is a standard `LoadError` by Ruby, which means that you either tried to require something in an illegal way or that your `$LOAD_PATH` is not what you think it is.

Closing this issue.

**Closed by jarmo** 2019-08-15 06:40 UTC
