### ISSUE TITLE
Trying to use `require_all` with a folder of the same name as the target file fails

### ISSUE THREAD

**Issue by kotp** [jarmo/require_all#27] opened 2018-04-04 04:07 UTC
Exercism/Ruby track has a folder in the `lib` folder that has the same name as a file that is wanted to be required (except for the extension of `.rb`).  This seems to be failing to load due to this, as another file name requested does load.

```
/home/kotp/projects/exercism/ruby/lib
bookkeeping.md
disable_skip.rb
generator
generator.rb
helper.rb
tasks
 => ["pwd", "ls -1"]
2.4.1 :004 > require_all '.'
LoadError: cannot load such file -- lib/generator.rb
        from /home/kotp/projects/exercism/ruby/lib/generator/exercise.rb:1:in `load'
        from /home/kotp/projects/exercism/ruby/lib/generator/exercise.rb:1:in `<top (required)>'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:208:in `require'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:208:in `__require'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:98:in `block in require_all'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:118:in `block in require_rel'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:117:in `each'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:117:in `require_rel'
        from /home/kotp/projects/exercism/ruby/lib/generator.rb:2:in `<top (required)>'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:208:in `require'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:208:in `__require'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:98:in `block in require_all'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
        from /home/kotp/.rvm/gems/ruby-2.4.1/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
        from (irb):4
        from /home/kotp/.rvm/rubies/ruby-2.4.1/bin/irb:11:in `<main>'
```

**Comment by enkessler** [comment] 2018-04-04 15:55
This doesn't look like a problem of files and folders having the same name, nor should that be a problem for  `require_all` in the first place. It looks like a problem with where the command is being run (i.e. the PWD). If you are already in `lib`, then it is no surprise that it cannot find a file `lib/generator.rb` because there is no `lib` folder inside the `lib` folder.

**Comment by jarmo** [comment] 2018-04-04 17:44
I agree that this seems to be a problem with the working directory. Please provide us a full reproducible code if you still think that this is really a bug in require_all.

Closing until that.

**Closed by jarmo** 2018-04-04 17:44 UTC
